CREATE TABLE CATEGORIE (
  ID_CAT INTEGER PRIMARY KEY,
  NOM    VARCHAR(255) NOT NULL
);

CREATE TABLE USER (
  EMAIL  VARCHAR(255) PRIMARY KEY,
  PSEUDO VARCHAR(255)
);

CREATE TABLE BILLET (
  TITRE      VARCHAR(255),
  ID_CAT     INTEGER REFERENCES CATEGORIE (ID_CAT),
  USER_EMAIL VARCHAR(255) REFERENCES USER (EMAIL),
  CONTENU    TEXT,
  PRIMARY KEY (ID_CAT, TITRE)
);

-- Utilisé pour la génération d'identifiants entiers
CREATE SEQUENCE hibernate_sequence;
